/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  RandomlyAssigned,
  RandomlyAssignedInterface,
} from "../RandomlyAssigned";

const _abi = [
  {
    inputs: [],
    name: "availableTokenCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxAvailableSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class RandomlyAssigned__factory {
  static readonly abi = _abi;
  static createInterface(): RandomlyAssignedInterface {
    return new utils.Interface(_abi) as RandomlyAssignedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RandomlyAssigned {
    return new Contract(address, _abi, signerOrProvider) as RandomlyAssigned;
  }
}
